PROFILE_NAME="Xiaomi Pad 8 Pro"
TARGET_MODEL="25091RP04C"
TARGET_DEVICE="piano"
TARGET_NAME="piano"
TARGET_BRAND="Xiaomi"
TARGET_MANUFACTURER="Xiaomi"
TARGET_MARKETNAME="Xiaomi Pad 8 Pro"
TARGET_DISPLAY_ID="OS3.0.11.0.WPYCNXM"
TARGET_HOSTNAME="Xiaomi-Pad-8-Pro"
TARGET_RAM="17179869184"
